# Generated by Django 4.0.3 on 2022-04-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FileField(null=True, upload_to='files/', verbose_name='')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
    ]
